package ija.ui;

import ija.elements.ALL;
import ija.elements.hraci;
import ija.homework2.board.MazeBoard;
import ija.homework1.treasure.CardPack;
import ija.homework1.treasure.TreasureCard;
import ija.homework1.treasure.Treasure;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author blaa
 */
public class menuGui extends javax.swing.JFrame {

    /**
     * Creates new form menuGui
     */
    public menuGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ParentPanel = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pozadieMenu = new javax.swing.JLabel();
        NastaveniaPanel = new javax.swing.JPanel();
        pocetHracov = new javax.swing.JLabel();
        pocetHracovSlider = new javax.swing.JSlider();
        pocetHracovText = new javax.swing.JTextField();
        velkostPola = new javax.swing.JLabel();
        velkostPolaSlider = new javax.swing.JSlider();
        velkostPolaText = new javax.swing.JTextField();
        velkostPola1 = new javax.swing.JLabel();
        Start = new javax.swing.JButton();
        NavratDoMenu = new javax.swing.JButton();
        tlacitko12 = new javax.swing.JRadioButton();
        tlacitko24 = new javax.swing.JRadioButton();
        pozadieNastavenia = new javax.swing.JLabel();
        hraPanel = new javax.swing.JPanel();
        hraciaPlochaGUI1 = new ija.ui.hraciaPlochaGUI();
        kartaHraca = new javax.swing.JLabel();
        balicekKarty = new javax.swing.JLabel();
        UkoncitHru = new javax.swing.JButton();
        ulozitHru = new javax.swing.JButton();
        potiahnutKartu = new javax.swing.JButton();
        dalsiHrac = new javax.swing.JButton();
        infoKarty = new javax.swing.JLabel();
        tah = new javax.swing.JLabel();
        naTahu = new javax.swing.JLabel();
        PocetHracoShow = new javax.swing.JLabel();
        skore = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        infoScore = new javax.swing.JLabel();
        infoKarta = new javax.swing.JLabel();
        pozadieHry = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        ParentPanel.setMinimumSize(new java.awt.Dimension(1024, 768));
        ParentPanel.setName(""); // NOI18N
        ParentPanel.setLayout(new java.awt.CardLayout());

        MenuPanel.setMinimumSize(new java.awt.Dimension(1024, 768));
        MenuPanel.setPreferredSize(new java.awt.Dimension(1024, 768));
        MenuPanel.setLayout(null);

        jButton1.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButton1.setText("NOVA HRA");
        jButton1.setMaximumSize(new java.awt.Dimension(90, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(90, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(90, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        MenuPanel.add(jButton1);
        jButton1.setBounds(370, 200, 260, 90);

        jButton2.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButton2.setText("NACITAT HRU");
        jButton2.setMaximumSize(new java.awt.Dimension(90, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(90, 25));
        jButton2.setPreferredSize(new java.awt.Dimension(90, 25));
        MenuPanel.add(jButton2);
        jButton2.setBounds(370, 360, 260, 90);

        jButton4.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButton4.setText("OPUSTIT HRU");
        jButton4.setMaximumSize(new java.awt.Dimension(90, 25));
        jButton4.setMinimumSize(new java.awt.Dimension(90, 25));
        jButton4.setPreferredSize(new java.awt.Dimension(90, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        MenuPanel.add(jButton4);
        jButton4.setBounds(370, 530, 260, 90);

        pozadieMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ija/ui/black.jpg"))); // NOI18N
        MenuPanel.add(pozadieMenu);
        pozadieMenu.setBounds(0, 0, 1024, 768);

        ParentPanel.add(MenuPanel, "card3");

        NastaveniaPanel.setMaximumSize(new java.awt.Dimension(1024, 768));
        NastaveniaPanel.setMinimumSize(new java.awt.Dimension(1024, 768));
        NastaveniaPanel.setLayout(null);

        pocetHracov.setFont(new java.awt.Font("Dodger", 1, 18)); // NOI18N
        pocetHracov.setForeground(new java.awt.Color(240, 240, 240));
        pocetHracov.setText("pocet hracov:");
        NastaveniaPanel.add(pocetHracov);
        pocetHracov.setBounds(370, 180, 260, 30);

        pocetHracovSlider.setMaximum(4);
        pocetHracovSlider.setMinimum(2);
        pocetHracovSlider.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pocetHracovSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pocetHracovSliderStateChanged(evt);
            }
        });
        NastaveniaPanel.add(pocetHracovSlider);
        pocetHracovSlider.setBounds(360, 210, 260, 50);

        pocetHracovText.setFont(new java.awt.Font("Century", 0, 24)); // NOI18N
        pocetHracovText.setText("2");
        NastaveniaPanel.add(pocetHracovText);
        pocetHracovText.setBounds(640, 210, 50, 50);

        velkostPola.setFont(new java.awt.Font("Dodger", 1, 18)); // NOI18N
        velkostPola.setForeground(new java.awt.Color(240, 240, 240));
        velkostPola.setText("velkost pola:");
        NastaveniaPanel.add(velkostPola);
        velkostPola.setBounds(370, 300, 260, 30);

        velkostPolaSlider.setMaximum(11);
        velkostPolaSlider.setMinimum(5);
        velkostPolaSlider.setValue(7);
        velkostPolaSlider.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        velkostPolaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                velkostPolaSliderStateChanged(evt);
            }
        });
        NastaveniaPanel.add(velkostPolaSlider);
        velkostPolaSlider.setBounds(360, 330, 260, 50);

        velkostPolaText.setFont(new java.awt.Font("Century", 0, 24)); // NOI18N
        velkostPolaText.setText("7");
        NastaveniaPanel.add(velkostPolaText);
        velkostPolaText.setBounds(640, 330, 50, 50);

        velkostPola1.setFont(new java.awt.Font("Dodger", 1, 20)); // NOI18N
        velkostPola1.setForeground(new java.awt.Color(240, 240, 240));
        velkostPola1.setText("Pocet KARIET/Predmetov:");
        NastaveniaPanel.add(velkostPola1);
        velkostPola1.setBounds(290, 430, 470, 30);

        Start.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        Start.setText("START");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        NastaveniaPanel.add(Start);
        Start.setBounds(800, 640, 170, 60);

        NavratDoMenu.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        NavratDoMenu.setText("NAVRAT DO MENU");
        NavratDoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavratDoMenuActionPerformed(evt);
            }
        });
        NastaveniaPanel.add(NavratDoMenu);
        NavratDoMenu.setBounds(40, 640, 170, 60);

        buttonGroup1.add(tlacitko12);
        tlacitko12.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        tlacitko12.setSelected(true);
        tlacitko12.setText("12");
        tlacitko12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        NastaveniaPanel.add(tlacitko12);
        tlacitko12.setBounds(320, 490, 60, 40);

        buttonGroup1.add(tlacitko24);
        tlacitko24.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        tlacitko24.setText("24");
        tlacitko24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        NastaveniaPanel.add(tlacitko24);
        tlacitko24.setBounds(610, 490, 60, 40);

        pozadieNastavenia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ija/ui/black2.jpg"))); // NOI18N
        NastaveniaPanel.add(pozadieNastavenia);
        pozadieNastavenia.setBounds(0, -40, 1030, 840);

        ParentPanel.add(NastaveniaPanel, "card2");

        hraPanel.setMaximumSize(new java.awt.Dimension(1024, 768));
        hraPanel.setMinimumSize(new java.awt.Dimension(1024, 768));
        hraPanel.setPreferredSize(new java.awt.Dimension(1024, 768));
        hraPanel.setLayout(null);
        hraPanel.add(hraciaPlochaGUI1);
        hraciaPlochaGUI1.setBounds(40, 30, 600, 600);

        kartaHraca.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        kartaHraca.setForeground(new java.awt.Color(240, 240, 240));
        kartaHraca.setText("0");
        hraPanel.add(kartaHraca);
        kartaHraca.setBounds(820, 280, 40, 40);

        balicekKarty.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        balicekKarty.setForeground(new java.awt.Color(240, 240, 240));
        balicekKarty.setText("0");
        hraPanel.add(balicekKarty);
        balicekKarty.setBounds(820, 190, 90, 40);

        UkoncitHru.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        UkoncitHru.setText("UKONCIT HRU >> NAVRAT DO MENU");
        UkoncitHru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UkoncitHruActionPerformed(evt);
            }
        });
        hraPanel.add(UkoncitHru);
        UkoncitHru.setBounds(700, 10, 310, 30);

        ulozitHru.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        ulozitHru.setText("ULOZIT HRU");
        hraPanel.add(ulozitHru);
        ulozitHru.setBounds(700, 50, 310, 30);

        potiahnutKartu.setText("POTIAHNUT KARTU");
        potiahnutKartu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 4, true));
        potiahnutKartu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potiahnutKartuActionPerformed(evt);
            }
        });
        hraPanel.add(potiahnutKartu);
        potiahnutKartu.setBounds(730, 340, 200, 30);

        dalsiHrac.setText("DALSI HRAC");
        dalsiHrac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dalsiHracActionPerformed(evt);
            }
        });
        hraPanel.add(dalsiHrac);
        dalsiHrac.setBounds(900, 610, 110, 120);

        infoKarty.setBackground(new java.awt.Color(0, 0, 0));
        infoKarty.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        infoKarty.setForeground(new java.awt.Color(240, 240, 240));
        infoKarty.setText("POCET KARIET V BALICKU:");
        infoKarty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        hraPanel.add(infoKarty);
        infoKarty.setBounds(700, 160, 270, 26);

        tah.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        tah.setForeground(new java.awt.Color(240, 240, 240));
        tah.setText("1");
        tah.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hraPanel.add(tah);
        tah.setBounds(210, 670, 20, 40);

        naTahu.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        naTahu.setForeground(new java.awt.Color(240, 240, 240));
        naTahu.setText("na tahu je hrac: =>");
        naTahu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hraPanel.add(naTahu);
        naTahu.setBounds(30, 670, 180, 40);

        PocetHracoShow.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        PocetHracoShow.setForeground(new java.awt.Color(240, 240, 240));
        PocetHracoShow.setText("...");
        PocetHracoShow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hraPanel.add(PocetHracoShow);
        PocetHracoShow.setBounds(30, 710, 350, 40);

        skore.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        skore.setForeground(new java.awt.Color(240, 240, 240));
        skore.setText("0");
        hraPanel.add(skore);
        skore.setBounds(820, 400, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ija/ui/example.JPG"))); // NOI18N
        hraPanel.add(jLabel1);
        jLabel1.setBounds(50, 40, 600, 600);

        infoScore.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        infoScore.setForeground(new java.awt.Color(240, 240, 240));
        infoScore.setText("TVOJE SKORE JE :");
        infoScore.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 2, true));
        hraPanel.add(infoScore);
        infoScore.setBounds(750, 380, 180, 20);

        infoKarta.setBackground(new java.awt.Color(0, 0, 0));
        infoKarta.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        infoKarta.setForeground(new java.awt.Color(240, 240, 240));
        infoKarta.setText("TVOJA KARTA JE:");
        infoKarta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        hraPanel.add(infoKarta);
        infoKarta.setBounds(740, 250, 180, 26);

        pozadieHry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ija/ui/black3.jpg"))); // NOI18N
        hraPanel.add(pozadieHry);
        pozadieHry.setBounds(0, 0, 1024, 768);

        ParentPanel.add(hraPanel, "card4");

        getContentPane().add(ParentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ParentPanel.removeAll();
        ParentPanel.add(NastaveniaPanel);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NavratDoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavratDoMenuActionPerformed
        ParentPanel.removeAll();
        ParentPanel.add(MenuPanel);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_NavratDoMenuActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        ParentPanel.removeAll();
        ParentPanel.add(hraPanel);
        ParentPanel.repaint();
        ParentPanel.revalidate();
        PocetHracoShow.setText("POCET HRACOV JE -> "+Integer.toString(pocetHracovSlider.getValue()));
        if(tlacitko12.isSelected())
        {
            CardPack novybalicek = new CardPack(12,12);
            ALL.balicekKariet = novybalicek;
            balicekKarty.setText(Integer.toString(novybalicek.size()));
            //balicekKarty.setText("ahoj");
        }
        else
        {
            //vygeneruj 24 kariet
            CardPack novybalicek = new CardPack(24,24);
            balicekKarty.setText(Integer.toString(novybalicek.size()));
        }
        hraciaPlochaGUI1.removeAll();
        MazeBoard hraciaPlocha = MazeBoard.createMazeBoard(velkostPolaSlider.getValue());
        ALL.hraciePole = hraciaPlocha;
        hraciaPlochaGUI1.vytvorGui();
        hraci zoznamHracov = hraci.vytvorHracov(pocetHracovSlider.getValue(),velkostPolaSlider.getValue(),velkostPolaSlider.getValue());
        ALL.poleHracov = zoznamHracov;
        hraciaPlochaGUI1.vytvorGui();
    }//GEN-LAST:event_StartActionPerformed

    private void pocetHracovSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pocetHracovSliderStateChanged
        pocetHracovText.setText(Integer.toString(pocetHracovSlider.getValue()));
    }//GEN-LAST:event_pocetHracovSliderStateChanged

    private void velkostPolaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_velkostPolaSliderStateChanged
        velkostPolaText.setText(Integer.toString(velkostPolaSlider.getValue()));
    }//GEN-LAST:event_velkostPolaSliderStateChanged

    private void UkoncitHruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UkoncitHruActionPerformed
        ParentPanel.removeAll();
        ParentPanel.add(MenuPanel);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_UkoncitHruActionPerformed

    private void dalsiHracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dalsiHracActionPerformed
        ALL.hracNaTahu = ALL.hracNaTahu + 1;
        
        if(pocetHracovSlider.getValue() >= ALL.hracNaTahu)
        {
           tah.setText(Integer.toString(ALL.hracNaTahu));
        }
        else
        {
           ALL.hracNaTahu = 1;
           tah.setText(Integer.toString(ALL.hracNaTahu));
           
        }
        if(ALL.poleHracov.poleHracov[ALL.hracNaTahu].uloha == -1)
        {
            kartaHraca.setText("");
        }
        else
        {
            kartaHraca.setText(Integer.toString(ALL.poleHracov.poleHracov[ALL.hracNaTahu].uloha));
        }
        
        
        // + treba pridat podmienku 
        // ak nasledujuci hrac (s cislom hracTeraz) ma kartu tak sa nastavi
        // potiahnutie karty na disable ... 
        // potiahnutKartu.setEnabled(false);
    }//GEN-LAST:event_dalsiHracActionPerformed

    private void potiahnutKartuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potiahnutKartuActionPerformed
        //if(ALL.poleHracov.poleHracov[ALL.hracNaTahu].uloha == -1)
        //{
        // ALL.poleHracov.poleHracov[ALL.hracNaTahu].uloha = ALL.balicekKariet.popCard().getCard().getCode();
        //kartaHraca.setText(Integer.toString(ALL.poleHracov.poleHracov[ALL.hracNaTahu].uloha));
        //}
        if(ALL.poleHracov.poleHracov[ALL.hracNaTahu].uloha == -1)
        {

            if( ALL.balicekKariet.size() != 0) 
            {
                //kartaHraca.setText(Integer.toString(ALL.balicekKariet.popCard().getCard().getCode()));
                ALL.poleHracov.poleHracov[ALL.hracNaTahu].uloha = ALL.balicekKariet.popCard().getCard().getCode();
                kartaHraca.setText(Integer.toString(ALL.poleHracov.poleHracov[ALL.hracNaTahu].uloha));
            }
        }
    }//GEN-LAST:event_potiahnutKartuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuGui().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel NastaveniaPanel;
    private javax.swing.JButton NavratDoMenu;
    private javax.swing.JPanel ParentPanel;
    private javax.swing.JLabel PocetHracoShow;
    private javax.swing.JButton Start;
    private javax.swing.JButton UkoncitHru;
    private javax.swing.JLabel balicekKarty;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton dalsiHrac;
    private javax.swing.JPanel hraPanel;
    private ija.ui.hraciaPlochaGUI hraciaPlochaGUI1;
    private javax.swing.JLabel infoKarta;
    private javax.swing.JLabel infoKarty;
    private javax.swing.JLabel infoScore;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel kartaHraca;
    private javax.swing.JLabel naTahu;
    private javax.swing.JLabel pocetHracov;
    private javax.swing.JSlider pocetHracovSlider;
    private javax.swing.JTextField pocetHracovText;
    private javax.swing.JButton potiahnutKartu;
    private javax.swing.JLabel pozadieHry;
    private javax.swing.JLabel pozadieMenu;
    private javax.swing.JLabel pozadieNastavenia;
    private javax.swing.JLabel skore;
    private javax.swing.JLabel tah;
    private javax.swing.JRadioButton tlacitko12;
    private javax.swing.JRadioButton tlacitko24;
    private javax.swing.JButton ulozitHru;
    private javax.swing.JLabel velkostPola;
    private javax.swing.JLabel velkostPola1;
    private javax.swing.JSlider velkostPolaSlider;
    private javax.swing.JTextField velkostPolaText;
    // End of variables declaration//GEN-END:variables
}
